spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/spring_test
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: MASTER-POOL
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

    slave:
      jdbc-url: jdbc:mysql://localhost:3307/spring_test
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: SLAVE-POOL
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        read-only: true
